Enabling the latest Graphviz attributes & shapes
ronsavage/GraphViz2 pull request #12
Opened 2022-07-19 21:53 UTC by nowthis

Resolves graphviz-perl/GraphViz2#11.

High-level summary of the 3 commits:
* The scripts reading values from graphviz.org pages are updated to adapt to that site's current format.
* All new known shapes and attributes are enabled in `GraphViz2.pm`.
* A test exercising the `class` attribute is added.
  * Inside the test script are comments documenting steps walking through how to see some sample CSS effects on the test's output.
  * Documentation of the results of those steps is posted at https://github.com/nowthis/GraphViz2/commit/1f25b684e1694eca782d82470f6bf131a5a9935f#comments

2022-07-20 19:50 UTC, mohawk2 requested changes
Thank you for these! Just a couple of tweaks.

2022-07-20 19:50 UTC, mohawk2 commented on scripts/extract.arrow.shapes.pl
> +my @shape = grep { length $_ } map { $_->as_text() } @td;
Could you switch this to the form `grep length, map $_->as_text, @td`? It's slightly more efficient in not creating block contexts, as well as more concise.

2022-07-20 19:50 UTC, mohawk2 commented on scripts/extract.attributes.pl
> +for my $c0 (map { $_->as_text() } @td) {
Same here.

2022-07-20 23:31 UTC, nowthis commented
I've made the requested change in new commit 341c6f6

2022-07-21 12:45 UTC, mohawk2 approved these changes

2022-07-21 12:46 UTC, merged

2022-07-21 12:49 UTC, mohawk2 commented
Released as 2.67. Thanks!